//
// Created by baby-benz on 7/15/2022.
//

#ifndef INC_3_LONGEST_SUBSTRING_WITHOUT_REPEATING_CHARACTERS_LENGTH_OF_LONGEST_SUBSTRING_H
#define INC_3_LONGEST_SUBSTRING_WITHOUT_REPEATING_CHARACTERS_LENGTH_OF_LONGEST_SUBSTRING_H

unsigned int lengthOfLongestSubstring(const char *s);

#endif //INC_3_LONGEST_SUBSTRING_WITHOUT_REPEATING_CHARACTERS_LENGTH_OF_LONGEST_SUBSTRING_H
